import './login/view login.cy'
import './login/login gagal.cy'
import './login/login.cy'
import './account/bm/view list bm.cy'
import './account/bm/view add page.cy'
import './account/bm/add bm fail.cy'
import './account/bm/add bm.cy'
import './account/bm/view detail bm.cy'
import './account/bm/view edit page bm.cy'
import './account/bm/edit bm fail.cy'
import './account/bm/edit bm.cy'
import './account/bm/view reset password bm.cy'
import './account/bm/reset password bm.cy'
import './account/bm/view delete bm.cy'
import './account/bm/delete bm.cy'
import './account/administrator/view list admin.cy'
import './account/administrator/view add admin page.cy'
import './account/administrator/add admin fail.cy'
import './account/administrator/add admin.cy'
import './account/administrator/view detail admin.cy'
import './account/administrator/view edit page admin.cy'
import './account/administrator/edit admin fail.cy'
import './account/administrator/edit admin.cy'
import './account/administrator/view reset password admin.cy'
import './account/administrator/reset password admin.cy'
import './account/administrator/view delete admin.cy'
import './account/administrator/delete admin.cy'