import './login/view login.cy'
import './login/login gagal.cy'
import './login/login.cy'
import './menu bm/view list bm.cy'
import './menu bm/view add page.cy'
import './menu bm/add bm fail.cy'
import './menu bm/add bm.cy'
import './menu bm/view detail bm.cy'
import './menu bm/view edit page bm.cy'
import './menu bm/edit bm fail.cy'
import './menu bm/edit bm.cy'
import './menu bm/view reset password bm.cy'
import './menu bm/reset password bm.cy'
import './menu bm/view delete bm.cy'
import './menu bm/delete bm.cy'